### ISSUE TITLE
Force log flushing

### ISSUE THREAD

**Issue by mayorova** [3scale/xcflushd#15]
Standard Ruby logger buffers the messages before printing them out to STDOUT. For this reason, the logs are sometimes not seen in the container logs.

A quick fix for that is to include:
```
STDOUT.sync = true
```
which forces the logs to be printed immediately.

This is not optimal, though. We need to review the logging and probably do the sync periodically.

**Comment by davidor** [comment]
I could only reproduce this using docker and without specifying the `--interactive` option.
